#
# Copyright © 2022-2024 Agence du Numérique en Santé (ANS) (https://esante.gouv.fr)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

groups:
- name: pscload
  rules:
# DELETING RULES
#
#
  - alert: pscload-critical-adeli-delete-size
    expr: ps_metric{idType="ADELI",operation="delete"} > scalar(ps_metric{idType="ADELI",operation="reference"}/100)
    labels:
      severity: critical
    annotations:
      summary: Total ADELI delete = {{$value}}
  - alert: pscload-critical-finess-delete-size
    expr: ps_metric{idType="FINESS",operation="delete"} > scalar(ps_metric{idType="FINESS",operation="reference"}/100)
    labels:
      severity: critical
    annotations:
      summary: Total FINESS delete = {{$value}}
  - alert: pscload-critical-siret-delete-size
    expr: ps_metric{idType="SIRET",operation="delete"} > scalar(ps_metric{idType="SIRET",operation="reference"}/100)
    labels:
      severity: critical
    annotations:
      summary: Total SIRET delete = {{$value}}
  - alert: pscload-critical-rpps-delete-size
    expr: ps_metric{idType="RPPS",operation="delete"} > scalar(ps_metric{idType="RPPS",operation="reference"}/100)
    labels:
      severity: critical
    annotations:
      summary: Total RPPS delete = {{$value}}
# UPDATING RULES
#
#
  - alert: pscload-critical-adeli-update-size
    expr: sum(ps_metric{idType="ADELI",operation="update"}) > scalar(ps_metric{idType="ADELI",operation="reference"}*5/100)
    labels:
      severity: critical
    annotations:
      summary: Total ADELI updates = {{$value}}
  - alert: pscload-critical-finess-update-size
    expr: sum(ps_metric{idType="FINESS",operation="update"}) > scalar(ps_metric{idType="FINESS",operation="reference"}*5/100)
    labels:
      severity: critical
    annotations:
      summary: Total FINESS updates = {{$value}}
  - alert: pscload-critical-siret-update-size
    expr: sum(ps_metric{idType="SIRET",operation="update"}) > scalar(ps_metric{idType="SIRET",operation="reference"}*5/100)
    labels:
      severity: critical
    annotations:
      summary: Total SIRET updates = {{$value}}
  - alert: pscload-critical-rpps-update-size
    expr: sum(ps_metric{idType="RPPS",operation="update"}) > scalar(ps_metric{idType="RPPS",operation="reference"}*5/100)
    labels:
      severity: critical
    annotations:
      summary: Total RPPS updates = {{$value}}

  - alert: pscload-continue
    expr: pscload_stage == 50
    for: 2m
    labels:
      severity: continue
    annotations:
      summary: RASS metrics OK